Fix build issue in DeblockTest
1) Removed reference function "aom_lpf_vertical_6_c" in loopfilter_ref.h
to avoid build issue:

test/loopfilter_ref.h:436:77: error: ‘void aom_lpf_vertical_6_c(uint8_t*, int, const uint8_t*, const uint8_t*, const uint8_t*)’ was declared ‘extern’ and later ‘static’ [-fpermissive]
    const uint8_t *limit, const uint8_t *thresh) {
In file included from /test/DeblockTest.cc:35:0:
/Source/Lib/Common/Codec/EbDeblockingFilter.h:226:10: note: previous declaration of ‘void aom_lpf_vertical_6_c(uint8_t*, int32_t, const uint8_t*, const uint8_t*, const uint8_t*)’
    void aom_lpf_vertical_6_c(uint8_t *s, int32_t pitch, const uint8_t *blimit, const uint8_t *limit, const uint8_t *thresh);          ^

2) Removed "static const int num_test = 28;"

3) Replaced "BW_CH" with "BW >> 1" for it was deleted.

4) Fiexed build issue for some functions being renamed.